Alchemy Websockets: Alchemy.Handlers.WebSocket.DataFrame Class Reference
Alchemy.Handlers.WebSocket.DataFrame Class Reference
Simple WebSocket data Frame implementation. Automatically manages adding received data to an existing frame and checking whether or not we've received the entire frame yet. See http://www.whatwg.org/specs/web-socket-protocol/ for more details on the WebSocket Protocol.
Public Types
enum DataFormat { Unknown = -1, Raw = 0, Frame = 1 }
enum DataState {
Empty = -1, Receiving = 0, Complete = 1, Waiting = 2,
Closed = 3, Ping = 4, Pong = 5
}
The Dataframe's state.
Public Member Functions
abstract DataFrame CreateInstance ()
abstract List< ArraySegment
< byte > > AsFrame ()
Converts the Payload to a websocket Frame.
abstract List< ArraySegment
< byte > > AsRaw ()
Converts the Payload to raw data.
void Reset ()
Resets and clears this instance.
void Append (String aString)
Appends the data.
abstract void Append (byte[] someBytes, bool asFrame=false)
Appends the data.
override string ToString ()
Public Attributes
DataFormat Format = DataFormat.Unknown
Protected Attributes
DataState InternalState = DataState.Empty
List< ArraySegment< byte > > Payload = new List<ArraySegment<byte>>()
The internal byte buffer used to store data.
Properties
UInt64 Length [get]
Gets the current length of the data.
DataState State [get, set]
Gets the state.
Detailed Description
Simple WebSocket data Frame implementation. Automatically manages adding received data to an existing frame and checking whether or not we've received the entire frame yet. See http://www.whatwg.org/specs/web-socket-protocol/ for more details on the WebSocket Protocol.
Definition at line 13 of file DataFrame.cs.
Member Enumeration Documentation
enum Alchemy::Handlers::WebSocket::DataFrame::DataFormat
Enumerator:
Unknown
Raw
Frame
Definition at line 19 of file DataFrame.cs.
enum Alchemy::Handlers::WebSocket::DataFrame::DataState
The Dataframe's state.
Enumerator:
Empty
Receiving
Complete
Waiting
Closed
Ping
Pong
Definition at line 33 of file DataFrame.cs.
Member Function Documentation
void Alchemy.Handlers.WebSocket.DataFrame.Append (String aString)
Appends the data.
Parameters:
aString Some data.
Definition at line 105 of file DataFrame.cs.
Referenced by Alchemy.WebSocketClient.Disconnect(), and Alchemy.Classes.UserContext.Send().
abstract void Alchemy.Handlers.WebSocket.DataFrame.Append (byte[] someBytes, bool asFrame = false) [pure virtual]
Appends the data.
Parameters:
someBytes Some data.
/
Parameters:
asFrame For internal use inside alchemy.
Implemented in Alchemy.Handlers.WebSocket.hybi10.DataFrame, and Alchemy.Handlers.WebSocket.hybi00.DataFrame.
abstract List<ArraySegment<byte> > Alchemy.Handlers.WebSocket.DataFrame.AsFrame () [pure virtual]
Converts the Payload to a websocket Frame.
Returns:
Implemented in Alchemy.Handlers.WebSocket.hybi10.DataFrame, and Alchemy.Handlers.WebSocket.hybi00.DataFrame.
Referenced by Alchemy.WebSocketClient.Disconnect(), and Alchemy.Handlers.Handler.Send().
abstract List<ArraySegment<byte> > Alchemy.Handlers.WebSocket.DataFrame.AsRaw () [pure virtual]
Converts the Payload to raw data.
Implemented in Alchemy.Handlers.WebSocket.hybi10.DataFrame, and Alchemy.Handlers.WebSocket.hybi00.DataFrame.
Referenced by Alchemy.Handlers.Handler.Send().
abstract DataFrame Alchemy.Handlers.WebSocket.DataFrame.CreateInstance () [pure virtual]
Implemented in Alchemy.Handlers.WebSocket.hybi10.DataFrame, and Alchemy.Handlers.WebSocket.hybi00.DataFrame.
Referenced by Alchemy.Classes.UserContext.Send().
void Alchemy.Handlers.WebSocket.DataFrame.Reset ()
Resets and clears this instance.
Definition at line 94 of file DataFrame.cs.
Referenced by Alchemy.Classes.Context.Reset().
override string Alchemy.Handlers.WebSocket.DataFrame.ToString ()
Definition at line 117 of file DataFrame.cs.
Member Data Documentation
DataFormat Alchemy.Handlers.WebSocket.DataFrame.Format = DataFormat.Unknown
Definition at line 48 of file DataFrame.cs.
DataState Alchemy.Handlers.WebSocket.DataFrame.InternalState = DataState.Empty [protected]
Definition at line 49 of file DataFrame.cs.
List<ArraySegment<byte> > Alchemy.Handlers.WebSocket.DataFrame.Payload = new List<ArraySegment<byte>>() [protected]
The internal byte buffer used to store data.
Definition at line 54 of file DataFrame.cs.
Property Documentation
UInt64 Alchemy.Handlers.WebSocket.DataFrame.Length [get]
Gets the current length of the data.
Definition at line 60 of file DataFrame.cs.
DataState Alchemy.Handlers.WebSocket.DataFrame.State [get, set]
Gets the state.
Definition at line 73 of file DataFrame.cs.
Referenced by Alchemy.Handlers.WebSocket.WebSocketHandler.HandleRequest(), and Alchemy.Classes.Context.Reset().
The documentation for this class was generated from the following file:
/Users/jlawson/Projects/Alchemy-Websockets/src/Alchemy/Handlers/WebSocket/DataFrame.cs