Alchemy Websockets: Alchemy.Classes.UserContext Class Reference
Alchemy.Classes.UserContext Class Reference
Contains data we will export to the Event Delegates.
Public Member Functions
UserContext (Context context)
Initializes a new instance of the UserContext class.
void OnConnect ()
Called when [connect].
void OnConnected ()
Called when [connected].
void OnDisconnect ()
Called when [disconnect].
void OnSend ()
Called when [send].
void OnReceive ()
Called when [receive].
void SetOnConnect (OnEventDelegate aDelegate)
Sets the on connect event.
void SetOnConnected (OnEventDelegate aDelegate)
Sets the on connected event.
void SetOnDisconnect (OnEventDelegate aDelegate)
Sets the on disconnect event.
void SetOnSend (OnEventDelegate aDelegate)
Sets the on send event.
void SetOnReceive (OnEventDelegate aDelegate)
Sets the on receive event.
void Send (DataFrame dataFrame, bool raw=false, bool close=false)
Sends the specified data.
void Send (String aString, bool raw=false, bool close=false)
Sends the specified data.
void Send (byte[] someBytes, bool raw=false, bool close=false)
Sends the specified data.
Public Attributes
EndPoint ClientAddress
The remote endpoint address.
Object Data
User defined data. Can be anything.
DataFrame DataFrame
The data Frame that this client is currently processing.
Protocol Protocol = Protocol.None
The type of connection this is.
string RequestPath = "/"
The path of this request.
Protected Attributes
OnEventDelegate OnConnectDelegate = x => { }
OnEvent Delegates specific to this connection.
OnEventDelegate OnConnectedDelegate = x => { }
OnEventDelegate OnDisconnectDelegate = x => { }
OnEventDelegate OnReceiveDelegate = x => { }
OnEventDelegate OnSendDelegate = x => { }
Properties
Header Header [get]
The internal context connection header.
UInt64 MaxFrameSize [get, set]
The maximum frame size.
Detailed Description
Contains data we will export to the Event Delegates.
Definition at line 10 of file UserContext.cs.
Constructor & Destructor Documentation
Alchemy.Classes.UserContext.UserContext (Context context)
Initializes a new instance of the UserContext class.
Parameters:
context The user context.
Definition at line 71 of file UserContext.cs.
Member Function Documentation
void Alchemy.Classes.UserContext.OnConnect ()
Called when [connect].
Definition at line 79 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
void Alchemy.Classes.UserContext.OnConnected ()
Called when [connected].
Definition at line 94 of file UserContext.cs.
Referenced by Alchemy.Handlers.Authentication.Authenticate().
void Alchemy.Classes.UserContext.OnDisconnect ()
Called when [disconnect].
Definition at line 109 of file UserContext.cs.
Referenced by Alchemy.Classes.Context.Dispose().
void Alchemy.Classes.UserContext.OnReceive ()
Called when [receive].
Definition at line 140 of file UserContext.cs.
Referenced by Alchemy.Handlers.WebSocket.WebSocketHandler.HandleRequest().
void Alchemy.Classes.UserContext.OnSend ()
Called when [send].
Definition at line 125 of file UserContext.cs.
void Alchemy.Classes.UserContext.Send (DataFrame dataFrame, bool raw = false, bool close = false)
Sends the specified data.
Parameters:
dataFrame The data.
raw Whether or not to send raw data
close if set to true [close].
Definition at line 203 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.Disconnect(), Alchemy.Handlers.WebSocket.WebSocketHandler.HandleRequest(), Alchemy.Handlers.Handler.ProcessHeader(), and Alchemy.WebSocketClient.Send().
void Alchemy.Classes.UserContext.Send (String aString, bool raw = false, bool close = false)
Sends the specified data.
Parameters:
aString The data.
raw whether or not to send raw data
close if set to true [close].
Definition at line 214 of file UserContext.cs.
void Alchemy.Classes.UserContext.Send (byte[] someBytes, bool raw = false, bool close = false)
Sends the specified data.
Parameters:
someBytes The data.
raw whether or not to send raw data
close if set to true [close].
Definition at line 227 of file UserContext.cs.
void Alchemy.Classes.UserContext.SetOnConnect (OnEventDelegate aDelegate)
Sets the on connect event.
Parameters:
aDelegate The Event Delegate.
Definition at line 156 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
void Alchemy.Classes.UserContext.SetOnConnected (OnEventDelegate aDelegate)
Sets the on connected event.
Parameters:
aDelegate The Event Delegate.
Definition at line 165 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
void Alchemy.Classes.UserContext.SetOnDisconnect (OnEventDelegate aDelegate)
Sets the on disconnect event.
Parameters:
aDelegate The Event Delegate.
Definition at line 174 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
void Alchemy.Classes.UserContext.SetOnReceive (OnEventDelegate aDelegate)
Sets the on receive event.
Parameters:
aDelegate The Event Delegate.
Definition at line 192 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
void Alchemy.Classes.UserContext.SetOnSend (OnEventDelegate aDelegate)
Sets the on send event.
Parameters:
aDelegate The Event Delegate.
Definition at line 183 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
Member Data Documentation
EndPoint Alchemy.Classes.UserContext.ClientAddress
The remote endpoint address.
Definition at line 20 of file UserContext.cs.
Referenced by Alchemy.WebSocketClient.OnRunClient().
Object Alchemy.Classes.UserContext.Data
User defined data. Can be anything.
Definition at line 25 of file UserContext.cs.
DataFrame Alchemy.Classes.UserContext.DataFrame
The data Frame that this client is currently processing.
Definition at line 30 of file UserContext.cs.
Referenced by Alchemy.Handlers.WebSocket.WebSocketHandler.HandleRequest(), Alchemy.WebSocketClient.OnRunClient(), Alchemy.Handlers.Handler.ProcessHeader(), and Alchemy.Classes.Context.Reset().
OnEventDelegate Alchemy.Classes.UserContext.OnConnectDelegate = x => { } [protected]
OnEvent Delegates specific to this connection.
Definition at line 35 of file UserContext.cs.
OnEventDelegate Alchemy.Classes.UserContext.OnConnectedDelegate = x => { } [protected]
Definition at line 36 of file UserContext.cs.
OnEventDelegate Alchemy.Classes.UserContext.OnDisconnectDelegate = x => { } [protected]
Definition at line 37 of file UserContext.cs.
OnEventDelegate Alchemy.Classes.UserContext.OnReceiveDelegate = x => { } [protected]
Definition at line 38 of file UserContext.cs.
OnEventDelegate Alchemy.Classes.UserContext.OnSendDelegate = x => { } [protected]
Definition at line 39 of file UserContext.cs.
Protocol Alchemy.Classes.UserContext.Protocol = Protocol.None
The type of connection this is.
Definition at line 51 of file UserContext.cs.
Referenced by Alchemy.Handlers.Authentication.Authenticate().
string Alchemy.Classes.UserContext.RequestPath = "/"
The path of this request.
Definition at line 56 of file UserContext.cs.
Referenced by Alchemy.Handlers.Authentication.Authenticate().
Property Documentation
Header Alchemy.Classes.UserContext.Header [get]
The internal context connection header.
Definition at line 45 of file UserContext.cs.
UInt64 Alchemy.Classes.UserContext.MaxFrameSize [get, set]
The maximum frame size.
Definition at line 62 of file UserContext.cs.
The documentation for this class was generated from the following file:
/Users/jlawson/Projects/Alchemy-Websockets/src/Alchemy/Classes/UserContext.cs