Alchemy Websockets: Alchemy.TcpServer Class Reference
Alchemy.TcpServer Class Reference
Public Member Functions
virtual void Start ()
Starts this instance.
virtual void Stop ()
Stops this instance.
virtual void Restart ()
Restarts this instance.
void Dispose ()
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
Protected Member Functions
TcpServer (int listenPort, IPAddress listenAddress)
abstract void OnRunClient (TcpClient connection)
Protected Attributes
int DefaultBufferSize = 512
Properties
int Port [get, set]
Gets or sets the port.
int ClientCount [get]
Gets the client count.
IPAddress ListenAddress [get, set]
Gets or sets the listener address.
Detailed Description
Definition at line 8 of file TCPServer.cs.
Constructor & Destructor Documentation
Alchemy.TcpServer.TcpServer (int listenPort, IPAddress listenAddress) [protected]
Definition at line 34 of file TCPServer.cs.
Member Function Documentation
void Alchemy.TcpServer.Dispose ()
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
Definition at line 196 of file TCPServer.cs.
abstract void Alchemy.TcpServer.OnRunClient (TcpClient connection) [protected, pure virtual]
Implemented in Alchemy.WebSocketServer, and Alchemy.AccessPolicyServer.
virtual void Alchemy.TcpServer.Restart () [virtual]
Restarts this instance.
Definition at line 123 of file TCPServer.cs.
virtual void Alchemy.TcpServer.Start () [virtual]
Starts this instance.
Reimplemented in Alchemy.WebSocketServer.
Definition at line 81 of file TCPServer.cs.
Referenced by Alchemy.TcpServer.Restart(), and Alchemy.WebSocketServer.Start().
virtual void Alchemy.TcpServer.Stop () [virtual]
Stops this instance.
Reimplemented in Alchemy.WebSocketServer.
Definition at line 102 of file TCPServer.cs.
Referenced by Alchemy.TcpServer.Dispose(), Alchemy.TcpServer.Restart(), and Alchemy.WebSocketServer.Stop().
Member Data Documentation
int Alchemy.TcpServer.DefaultBufferSize = 512 [protected]
Definition at line 20 of file TCPServer.cs.
Referenced by Alchemy.WebSocketServer.OnRunClient().
Property Documentation
int Alchemy.TcpServer.ClientCount [get]
Gets the client count.
Definition at line 62 of file TCPServer.cs.
IPAddress Alchemy.TcpServer.ListenAddress [get, set]
Gets or sets the listener address.
The listener address.
Definition at line 73 of file TCPServer.cs.
Referenced by Alchemy.WebSocketServer.Start().
int Alchemy.TcpServer.Port [get, set]
Gets or sets the port.
The port.
Definition at line 53 of file TCPServer.cs.
Referenced by Alchemy.Handlers.WebSocket.hybi00.Authentication.CheckAuthentication(), Alchemy.Handlers.WebSocket.hybi10.Authentication.CheckAuthentication(), and Alchemy.WebSocketServer.Start().
The documentation for this class was generated from the following file:
/Users/jlawson/Projects/Alchemy-Websockets/src/Alchemy/TCPServer.cs